# Generated by Django 4.1.7 on 2023-11-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coding_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Technology_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tool_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=255, null=True)),
                ('tools', models.ManyToManyField(blank=True, to='app.tool_list')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_status', models.CharField(choices=[('Active', 'Active'), ('Complete', 'Complete')], max_length=20, null=True)),
                ('technology', models.ManyToManyField(blank=True, to='app.technology_list')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('emp_status', models.CharField(choices=[('current-emp', 'Current-Emp'), ('ex-emp', 'Ex-Employee')], max_length=20, null=True)),
                ('coding_skills', models.ManyToManyField(blank=True, to='app.coding_list')),
                ('tools', models.ManyToManyField(blank=True, to='app.tool_list')),
            ],
        ),
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=255, null=True)),
                ('coding_skills', models.ManyToManyField(blank=True, to='app.coding_list')),
            ],
        ),
    ]
