# Generated by Django 4.2.6 on 2023-11-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='roles_responsibilities',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
