# Generated by Django 4.2.6 on 2023-11-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_description_project_roles_responsibilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='projects',
            field=models.ManyToManyField(blank=True, to='app.project'),
        ),
    ]
