# Generated by Django 4.2.6 on 2023-11-18 10:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_employees_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='roles_responsibilities',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
