# Generated by Django 4.2.6 on 2023-11-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_employees_professional_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='professional_summary',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
