# Generated by Django 4.2.6 on 2023-11-21 08:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_employees_professional_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='professional_summary',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
